name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools
        pip3 install --user -r sphinx-requirements.txt
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        make html
    - name: Push the docs
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847  # v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        publish_branch: latestHTML